# Generated by Django 2.1.7 on 2019-09-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='Data',
        ),
    ]
