# Generated by Django 2.1.7 on 2019-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190903_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
