# Generated by Django 2.1.7 on 2019-09-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_data1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='huilu',
        ),
        migrations.AddField(
            model_name='data',
            name='device',
            field=models.TextField(default='未定义'),
        ),
    ]
