# Generated by Django 2.1.7 on 2019-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_data_huilu'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='jihao',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
